export const ADD_QUOTELINE = "ADD_QUOTELINE";
export const REMOVE_QUOTELINE = "REMOVE_QUOTELINE";
export const CLONE_QUOTELINE = "CLONE_QUOTELINE";
export const REORDER_QUOTELINE = "REORDER_QUOTELINE";


export const ACTION_INITIALIZE_APP = "INITIALIZE_APP";

